project:
  type: website
  render:
    - "*.qmd"
    - "*.html"

website:
  title: "conradkay.com"
  site-url: https://blog.conradkay.com
  description: Conrad Kay's blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/conradbkay

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
